Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'graphQLOptions':
              position: 'before routing'
              component: 't3n\GraphQL\Http\HttpOptionsComponent'

t3n:
  GraphQL:
    context: 't3n\GraphQL\Context'
    includeExceptionMessageInOutput: true
    endpoints: []
#      'some-endpoint':
#        'context:' 'Foo\Vendor\GraphQL\Context  # optional context that overrides the global context
#        'schemaEnvelope': 'Some\Fully\Qualified\Namespace'
